{% set name = "aenum" %}
{% set version = "2.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 81828d1fbe20b6b188d75b21a0fa936d7d929d839ef843ef385d9c2a97082864

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - aenum
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://bitbucket.org/stoneleaf/aenum
  license: BSD-3-Clause
  license_family: BSD
  license_file: aenum/LICENSE
  summary: Advanced Enumerations (compatible with Python's stdlib Enum), NamedTuples,

extra:
  recipe-maintainers:
    - sodre
