{% set name = "aenum" %}
{% set version = "3.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3e531c91860a81f885f7e6e97d219ae9772cb899580084788935dad7d9742ef0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6

test:
  imports:
    - aenum
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://bitbucket.org/stoneleaf/aenum
  license: BSD-3-Clause
  license_family: BSD
  license_file: aenum/LICENSE
  summary: Advanced Enumerations (compatible with Python's stdlib Enum), NamedTuples,

extra:
  recipe-maintainers:
    - sodre
    - jan-janssen
