{% set name = "aenum" %}
{% set version = "2.2.3" %}
{% set sha256 = "a4334cabf47c167d44ab5a6198837b80deec5d5bad1b5cf70c966c3a330260e8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - aenum

about:
  home: https://bitbucket.org/stoneleaf/aenum
  license: BSD-3-Clause
  license_family: BSD
  license_file: aenum/LICENSE
  summary: Advanced Enumerations (compatible with Python's stdlib Enum), NamedTuples,

extra:
  recipe-maintainers:
    - sodre
