travis:
  secure:
    BINSTAR_TOKEN: mskPA8xgKj4xr1B2mQloRAznbndb7Va7Bye3axkqREhhIjOYW0tt8X7SACEBBstvX/UDZCrakJ8cpnWVXT4Z8bctM54g862JwemyAECOMAIRtYL3yzBTYjIl6ccIeUl48HjJxcj6cCpZu37m33LozOkm5H1XBEVN+HraiLqQywZPsyZ/p48MJU9BP+2iyHQMR9g0i8rRBLlDvlJsr35w1FQQTpe9Nb+qNV0cyXbIBn117i9JOee2oH4sOCrD+ftQQVzFA77veYiceFtSfOkgYP/8LWez2JZtYdc1SsTKOcMGsb96I/s/x4z2wLHLJC6uGzvoDLcGhd3cZy3LO3z4uKOHlE3TyKvhhRvfbEJAQqiIkd1ED/9UyQZ/5hSa9+4INe7BR7340PqQJX0UOQTXsmcUW4uWlbsP/TTWN0BnjMuSLfzBCE3dLO5ULrUxE+JXjVJhNxWYyf9C7fslpZX6HusuDlUmoNrqbd+mHQX4o1mzCdbxwSn6WYQAShLcRLGLd0u4FsUfLQOHF8fjgYwsO9irNWfUaay063pYFGmtq4B/3fChUfPn9T+axAkLZWPcuzW8qlXg5YhjCbw1dU2OGiBv2ibj/sXooHNKb2SH93P65SFCKdjAIJzyq522EbZhG4GbT9hYv/uxrxTFewZSq4aZ73MOe7lmvFjuciVpMoQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
